/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import controller.c_koneksi;
import controller.controllerToko;
import model.m_toko;


/**
 *
 * @author A455L
 */
public class home extends javax.swing.JFrame {
   

    controllerToko ctoko;
    List<m_toko> listdata = new ArrayList<>();
    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        ctoko = new controllerToko(this);
        ctoko.isiTable();
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kode = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        kategori = new javax.swing.JComboBox<>();
        jenis = new javax.swing.JComboBox<>();
        harga = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        quit = new javax.swing.JButton();
        CARI = new javax.swing.JButton();
        carikategori = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableData = new javax.swing.JTable();
        user = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        kode.setFont(new java.awt.Font("Bryndan Unifont", 0, 18)); // NOI18N
        kode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        kode.setBorder(null);
        kode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodeActionPerformed(evt);
            }
        });
        getContentPane().add(kode);
        kode.setBounds(140, 80, 210, 30);

        nama.setFont(new java.awt.Font("Bryndan Unifont", 0, 18)); // NOI18N
        nama.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nama.setBorder(null);
        getContentPane().add(nama);
        nama.setBounds(140, 120, 210, 30);

        kategori.setFont(new java.awt.Font("Bryndan Unifont", 0, 18)); // NOI18N
        kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan", "Barang", "Minuman" }));
        kategori.setBorder(null);
        kategori.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(kategori);
        kategori.setBounds(540, 40, 210, 30);

        jenis.setFont(new java.awt.Font("Bryndan Unifont", 0, 18)); // NOI18N
        jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pack ", "Sachet" }));
        jenis.setBorder(null);
        jenis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jenis);
        jenis.setBounds(540, 80, 210, 30);

        harga.setFont(new java.awt.Font("Bryndan Unifont", 0, 18)); // NOI18N
        harga.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        harga.setBorder(null);
        harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaActionPerformed(evt);
            }
        });
        getContentPane().add(harga);
        harga.setBounds(540, 120, 210, 30);

        jLabel1.setFont(new java.awt.Font("Bryndan Unifont", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Harga");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(450, 120, 80, 30);

        jLabel2.setFont(new java.awt.Font("Bryndan Unifont", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Kode Barang");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 80, 80, 30);

        jLabel3.setFont(new java.awt.Font("Bryndan Unifont", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 120, 80, 30);

        jLabel4.setFont(new java.awt.Font("Bryndan Unifont", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Kategori");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(450, 40, 80, 30);

        jLabel5.setFont(new java.awt.Font("Bryndan Unifont", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Jenis Packaging");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(430, 80, 110, 30);

        save.setBackground(new java.awt.Color(255, 255, 255));
        save.setFont(new java.awt.Font("Bryndan Unifont", 0, 18)); // NOI18N
        save.setText("SAVE");
        save.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save);
        save.setBounds(50, 200, 120, 30);

        edit.setBackground(new java.awt.Color(255, 255, 255));
        edit.setFont(new java.awt.Font("Bryndan Unifont", 0, 18)); // NOI18N
        edit.setText("EDIT");
        edit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        edit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit);
        edit.setBounds(190, 200, 120, 30);

        clear.setBackground(new java.awt.Color(255, 255, 255));
        clear.setFont(new java.awt.Font("Bryndan Unifont", 0, 18)); // NOI18N
        clear.setText("CLEAR");
        clear.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear);
        clear.setBounds(340, 200, 120, 30);

        delete.setBackground(new java.awt.Color(255, 255, 255));
        delete.setFont(new java.awt.Font("Bryndan Unifont", 0, 18)); // NOI18N
        delete.setText("DELETE");
        delete.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete);
        delete.setBounds(480, 200, 120, 30);

        quit.setBackground(new java.awt.Color(255, 255, 255));
        quit.setFont(new java.awt.Font("Bryndan Unifont", 0, 18)); // NOI18N
        quit.setText("QUIT");
        quit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        quit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitActionPerformed(evt);
            }
        });
        getContentPane().add(quit);
        quit.setBounds(620, 200, 120, 30);

        CARI.setFont(new java.awt.Font("Bryndan Unifont", 0, 18)); // NOI18N
        CARI.setText("CARI");
        CARI.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        CARI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CARI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CARIActionPerformed(evt);
            }
        });
        getContentPane().add(CARI);
        CARI.setBounds(570, 280, 90, 30);

        carikategori.setFont(new java.awt.Font("Bryndan Unifont", 0, 18)); // NOI18N
        carikategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan", "Barang", "Minuman" }));
        carikategori.setBorder(null);
        carikategori.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(carikategori);
        carikategori.setBounds(380, 280, 170, 30);

        jLabel6.setFont(new java.awt.Font("Bryndan Unifont", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Pencarian berdasarkan Kategori");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(160, 280, 220, 30);

        TableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "kode barang", "nama", "kategori", "jenis", "harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableData);
        if (TableData.getColumnModel().getColumnCount() > 0) {
            TableData.getColumnModel().getColumn(0).setResizable(false);
            TableData.getColumnModel().getColumn(1).setResizable(false);
            TableData.getColumnModel().getColumn(2).setResizable(false);
            TableData.getColumnModel().getColumn(3).setResizable(false);
            TableData.getColumnModel().getColumn(4).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 330, 680, 130);

        user.setFont(new java.awt.Font("Bryndan Unifont", 1, 18)); // NOI18N
        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        getContentPane().add(user);
        user.setBounds(140, 40, 80, 30);

        jLabel8.setFont(new java.awt.Font("Bryndan Unifont", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Admin");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 40, 60, 30);

        jLabel7.setFont(new java.awt.Font("Bryndan Unifont", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/2.png"))); // NOI18N
        jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(-4, -10, 810, 490);

        setSize(new java.awt.Dimension(814, 513));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        ctoko.SimpanData();
        ctoko.isiTable();




        // TODO add your handling code here:
    }//GEN-LAST:event_saveActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        ctoko.Ubah();
        ctoko.isiTable();
        


// TODO add your handling code here:
    }//GEN-LAST:event_editActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        ctoko.Reset();
        

        // TODO add your handling code here:
    }//GEN-LAST:event_clearActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        ctoko.Hapus();
        ctoko.isiTable();


        // TODO add your handling code here:
    }//GEN-LAST:event_deleteActionPerformed

    private void quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitActionPerformed
dispose();


// TODO add your handling code here:
    }//GEN-LAST:event_quitActionPerformed

    private void CARIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CARIActionPerformed

        ctoko.CariKategori();

        // TODO add your handling code here:
    }//GEN-LAST:event_CARIActionPerformed

    private void kodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kodeActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
 String halouser = login.user;
        user.setText(halouser);

        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void TableDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableDataMouseClicked

        int baris = TableData.getSelectedRow();
        
        if(baris != -1){
            kode.setText(TableData.getValueAt(baris, 0).toString());
            nama.setText(TableData.getValueAt(baris, 1).toString());
             kategori.setSelectedItem(TableData.getValueAt(baris, 2).toString());
              jenis.setSelectedItem(TableData.getValueAt(baris, 3).toString());
            harga.setText(TableData.getValueAt(baris, 4).toString());
           
        }        // TODO add your handling code here:
    }//GEN-LAST:event_TableDataMouseClicked

    public JTextField getTxtKode(){
        return kode;
    }
    public JTextField getTxtNama(){
        return nama;
    }
    public JTextField getTxtHarga(){
        return harga;
    }
    public JComboBox getCbKategori(){
        return kategori;
    }
    public JComboBox getCbJenis(){
        return jenis;
    }
    public JTable getTableData(){
        return TableData;
    }
     public JComboBox getCbCariKategori(){
        return carikategori;
    }
     public JButton getButtonSimpan(){
        return save;
    }
     public JButton getButtonHapus(){
        return delete;
    }
     public JButton getButtonBersihkan(){
        return clear;
    }
     public JButton getButtonKeluar(){
        return quit;
    }
     public JButton getButtonUbah(){
        return edit;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CARI;
    private javax.swing.JTable TableData;
    private javax.swing.JComboBox<String> carikategori;
    private javax.swing.JButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JTextField harga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jenis;
    private javax.swing.JComboBox<String> kategori;
    private javax.swing.JTextField kode;
    private javax.swing.JTextField nama;
    private javax.swing.JButton quit;
    private javax.swing.JButton save;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
